balukaa/balukaa/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from userapp.views import NewUserView, LedgerLoginView
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("ledger.urls")),
    path("register/", NewUserView.as_view()),
    path("login/", LedgerLoginView.as_view()),
    path("logout/", LogoutView.as_view()),
]


if settings.DEBUG:
    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

balukaa/registration/urls.py
import debug_toolbar
from django.urls import path
from .views import UserCreateView, UserLoginView, UserLogoutView

app_name = 'registration'
urlpatterns = [
    path('register/', UserCreateView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
]

balukaa/todo/urls.py
from django.urls import path
from .views import (
    TodoJournalListView,
)


app_name = 'todo'
urlpatterns = [
    path('todos_journal', TodoJournalListView.as_view(), name='todos_journal'),
]

balukaa/templates/includes/_cart_info.html
{% load static %}
<div class="card text-center text-body bg-info ledger-cart-info">
    <img class="p-5" src="{% static 'balukaa/images/info-square.svg' %}" width="100%">
    <div class="card-body">
        <h6 class="card-title">{{ cart_text }}</h6>
    </div>
</div>

balukaa/templates/includes/_nav_main.html
{% load static %}
{# ------- ГЛАВНОЕ МЕНЮ ------- #}
<nav class="navbar navbar-sm sticky-top navbar-expand-sm navbar-dark bg-dark p-0 px-md-4 mb-2 border-bottom shadow-sm">
    <div class="container-fluid">
        <ul class="navbar-nav">
            {# ------- ДОМАШНЯЯ СТРАНИЦА ------- #}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">Главная</a>
            </li>
            {# ------- ГРУППЫ И ПУНКТЫ НИСПАДАЮЩЕГО МЕНЮ ------- #}
            {% if user.is_authenticated %}
                {% regroup menu_list by item_group as menu %}
                {% for item in menu %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle"
                     href="#"
                     id="navbarDropdown{{ forloop.counter }}"
                     role="button"
                     data-bs-toggle="dropdown"
                     aria-expanded="false"
                    >
                        {{ item.grouper }}
                    </a>
                    <ul class="dropdown-menu dropdown-menu-dark"
                        aria-labelledby="navbarDropdown{{ forloop.counter }}"
                    >
                    {% for dropdown in item.list %}
                        <li>
                            <a class="dropdown-item" href="{{ dropdown.item_url }}"
                            >{{ dropdown.item_text }}</a>
                        </li>
                    {% endfor %}
                    </ul>
                </li>
                {% endfor %}
            {% endif %}
        </ul>
        {# ------- РЕГИСТРАЦИЯ, ЛОГИН, ЛОГАУТ ------- #}
        <ul class="navbar-nav d-flex">
            <li class="nav-item">
            {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'registration:logout' %}">
                    Выход <img src="{% static 'balukaa/images/box-arrow-right.svg' %}">
                </a>
            {% else %}
                <a class="nav-link" href="{% url 'registration:register' %}">
                    <img src="{% static 'balukaa/images/person-plus-fill.svg' %}"> Регистрация
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'registration:login' %}">
                    <img src="{% static 'balukaa/images/box-arrow-in-right.svg' %}"> Вход
                </a>
            </li>
            {% endif %}
            </li>
        </ul>
    </div>
</nav>