balukaa/balukaa/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from userapp.views import NewUserView, LedgerLoginView
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("ledger.urls")),
    path("register/", NewUserView.as_view()),
    path("login/", LedgerLoginView.as_view()),
    path("logout/", LogoutView.as_view()),
]


if settings.DEBUG:
    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

balukaa/ledger/urls.py
from django.urls import path
from .views import (
    AccountsBookListView, AccountView, AccountCreateView, AccountUpdateView, AccountDeleteView,
    EntriesJournalListView, EntryView, EntryCreateView, EntryUpdateView, EntryDeleteView,
    MovementsReportListView, AccountCardReportView, AccountBalanceReportView,
)


app_name = 'ledger'
urlpatterns = [
    path('accounts_book/', AccountsBookListView.as_view(), name='accounts_book'),
    path('account/<str:number>/', AccountView.as_view(), name='account_view'),
    path('account/create/', AccountCreateView.as_view(), name='account_create'),
    path('account/update/<str:number>/', AccountUpdateView.as_view(), name='account_update'),
    path('account/delete/<str:number>/', AccountDeleteView.as_view(), name='account_delete'),

    path('entries_journal', EntriesJournalListView.as_view(), name='entries_journal'),
    path('entry/<int:pk>/', EntryView.as_view(), name='entry_view'),
    path('entry/create/', EntryCreateView.as_view(), name='entry_create'),
    path('entry/update/<int:pk>/', EntryUpdateView.as_view(), name='entry_update'),
    path('entry/delete/<int:pk>/', EntryDeleteView.as_view(), name='entry_delete'),

    path('movements_report/', MovementsReportListView.as_view(), name='movements_report'),
    path('account_card_report/<str:number>', AccountCardReportView.as_view(), name='account_card_report'),
    path('account_balance_report/', AccountBalanceReportView.as_view(), name='account_balance_report'),
]

balukaa/todo/urls.py
from django.urls import path
from .views import (
    TodoJournalListView,
)


app_name = 'todo'
urlpatterns = [
    path('todos_journal', TodoJournalListView.as_view(), name='todos_journal'),
]

balukaa/todo/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from .services import work_up_string


class TodoEntry(models.Model):
    """ Записи журнала "Список дел"

    Для удобства date_range - CharField, а не DateField
    Идеальная точность для списка дел не важна, а для истории можно свободно записывать дату любых форматах:
    - "01.06.2021";
    - "июн.2021";
    - "май-июн.2021"
    - "25.мая-7.июн.2021"
    """
    class Statuses(models.IntegerChoices):
        """ Два состояния активности бухгалтерских проводок

        Отсюда:
        https://docs.djangoproject.com/en/3.0/ref/models/fields/#enumeration-types
        """
        ENABLE = 1, _('В работе')
        DISABLE = 0, _('Сделано')

    date_range = models.CharField(max_length=64, default="")
    task = models.CharField(max_length=64)
    description = models.CharField(max_length=256)
    status = models.IntegerField(
        choices=Statuses.choices,
        default=Statuses.ENABLE,
    )
    comment = models.CharField(max_length=256)
    creator = models.CharField(max_length=32)

    def __str__(self):
        return "%s, %s" % \
               (self.task,
                self.date_range)

    def get_description(self):
        return '%s, %s, %s, %s, %s, %s' % \
               (self.date_range,
                self.task,
                self.description,
                self.get_status(),
                self.comment,
                self.creator)

    def get_absolute_url(self):
        pass

    def get_status(self):
        return self.Statuses(self.status).label

    def date_range_map(self):
        return work_up_string(self.date_range)

    def task_map(self):
        return work_up_string(self.task)

    def description_map(self):
        return work_up_string(self.description)

    def status_map(self):
        return work_up_string(self.get_status())

    def comment_map(self):
        return work_up_string(self.comment)

    def creator_map(self):
        return work_up_string(self.creator)

    class Meta:
        verbose_name = "Задача"
        verbose_name_plural = "Задачи"

balukaa/ledger/forms.py
from datetime import date, datetime

from django import forms
from .models import LedgerAccount, LedgerEntry


class LedgerAccountForm(forms.ModelForm):
    number = forms.CharField(
        max_length=2,
        label='Номер счета',
        widget=forms.TextInput(
            attrs={'class': 'form-control'})
        )
    name = forms.CharField(
        max_length=32,
        label='Краткое имя счета',
        widget=forms.TextInput(
            attrs={'class': 'form-control'})
        )
    full_name = forms.CharField(
        max_length=64,
        label='Полное имя счета',
        widget=forms.TextInput(
            attrs={'class': 'form-control'})
        )
    type = forms.ChoiceField(
        label='Тип счета',
        choices=LedgerAccount.AccountTypes.choices,
        widget=forms.Select(
            attrs={'class': 'form-control'})
        )

    class Meta:
        model = LedgerAccount
        fields = ('number', 'name', 'full_name', 'type')         # fields = '__all__'


class LedgerEntryForm(forms.ModelForm):
    ''' Для удобства в поле date надо установить виджет какого-нибудь DatePicker

    Например, попробовать bootstrap_datepicker_plus, отсюда:
    https://question-it.com/questions/289488/kak-ispolzovat-sredstvo-vybora-daty-v-prostoj-forme-django
    '''
    date = forms.DateTimeField(
        label='Дата проводки',
        widget=forms.DateInput(
            attrs={'class': 'form-control',
                   'type': 'datetime-local'
                   }),
        initial=datetime.today(),
        localize=True
        )
    account_one = forms.ModelChoiceField(
        label='Счет 1',
        queryset=LedgerAccount.objects.order_by('number'),
        empty_label="Выберите счет 1",
        widget=forms.Select(
            attrs={'class': 'form-control'})
        )
    account_two = forms.ModelChoiceField(
        label='Счет 2',
        queryset=LedgerAccount.objects.order_by('number'),
        empty_label="Выберите счет 2",
        widget=forms.Select(
            attrs={'class': 'form-control'})
        )
    type = forms.ChoiceField(
        label='Тип проводки',
        choices=LedgerEntry.EntryTypes.choices,
        widget=forms.Select(
            attrs={'class': 'form-control'})
        )
    amount = forms.DecimalField(
        label='Сумма',
        widget=forms.NumberInput(
            attrs={'class': 'form-control'})
        )
    comment = forms.CharField(
        max_length=256,
        label='Комментарий',
        widget=forms.Textarea(
            attrs={'class': 'form-control',
                   'rows': 1})
        )
    status = forms.ChoiceField(
        label='Состояние проводки',
        choices=LedgerEntry.Statuses.choices,
        widget=forms.Select(
            attrs={'class': 'form-control'})
        )

    class Meta:
        model = LedgerEntry
        fields = ('date', 'account_one', 'account_two', 'type', 'amount', 'comment', 'status')

balukaa/ledger/views.py
import decimal
from typing import Any, Dict
from datetime import date, datetime, timedelta
from dataclasses import dataclass

from django.db.models.query import QuerySet
from django.db.models import Q
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.utils.formats import date_format
from django.views.generic import ListView, TemplateView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from .models import LedgerAccount, LedgerEntry
from .forms import LedgerEntryForm, LedgerAccountForm
from balukaa.nav_main_list import MENU


class AccountsBookListView(LoginRequiredMixin, ListView):
    model = LedgerAccount
    template_name = 'ledger/accounts_book.html'
    context_object_name = 'accounts'

    def get_context_data(self, **kwargs):
        """ Переменные шаблона

        title =     title сайта; заголовок navbar content
        btn_href =  ссылка для кнопки navbar content
        btn_text =  текст для кнопки navbar content
        cart_text = текст info-cart, вызываемой в случае отсутствия записей
        menu_list = список элементов dropdown меню: {item-group, item-text, item-url}
        """
        context = super().get_context_data(**kwargs)
        context['title'] = 'План счетов'
        context['btn_href'] = reverse_lazy('ledger:account_create')
        context['btn_text'] = 'Новый счет'
        context['cart_text'] = 'В плане счетов нет записей!'
        context['menu_list'] = MENU
        return context

    def get_queryset(self):
        return LedgerAccount.objects.all().order_by('number')


class AccountView(LoginRequiredMixin, DetailView):
    permission_required = 'account.view_choice'
    model = LedgerAccount
    template_name = 'ledger/account.html'
    context_object_name = 'account'

    def get_context_data(self, **kwargs):
        """ Переменные шаблона

        title =     title сайта; заголовок navbar content
        btn_href =  ссылка для кнопки navbar content
        btn_text =  текст для кнопки navbar content
        menu_list = список элементов dropdown меню: {item-group, item-text, item-url}
        """
        context = super().get_context_data(**kwargs)
        context['title'] = 'Бухгалтерский счет'
        context['btn_href'] = reverse_lazy('ledger:accounts_book')
        context['btn_text'] = 'План счетов'
        context['menu_list'] = MENU
        return context

    def get_object(self):
        """ Переопределяем стандартное получение объекта для DetailView по pk или slug на number

            Посмотрел здесь:
            https://stackru.com/questions/54206946/django-detailview-putanitsa-v-funktsii-getobject
        """
        return get_object_or_404(LedgerAccount, number=self.kwargs.get('number'))


class AccountCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'account.add_choice'
    model = LedgerAccount
    template_name = 'ledger/account_edit.html'   # account_create.html
    context_object_name = 'account'
    form_class = LedgerAccountForm

    def get_context_data(self, **kwargs):
        """ Переменные шаблона

        title =     title сайта; заголовок navbar content
        btn_href =  ссылка для кнопки navbar content
        btn_text =  текст для кнопки navbar content
        menu_list = список элементов dropdown меню: {item-group, item-text, item-url}
        """
        context = super().get_context_data(**kwargs)
        context['title'] = f"Создать бухгалтерский счет"
        context['btn_href'] = reverse_lazy('ledger:accounts_book')
        context['btn_text'] = 'План счетов'
        context['menu_list'] = MENU
        return context


class AccountUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'account.change_choice'
    model = LedgerAccount
    template_name = 'ledger/account_edit.html'
    context_object_name = 'account'
    form_class = LedgerAccountForm

    def get_context_data(self, **kwargs):
        """ Переменные шаблона

        title =     title сайта; заголовок navbar content
        btn_href =  ссылка для кнопки navbar content
        btn_text =  текст для кнопки navbar content
        menu_list = список элементов dropdown меню: {item-group, item-text, item-url}
        """
        context = super().get_context_data(**kwargs)
        context['title'] = f"Изменить бухгалтерский счет { self.kwargs.get('number') }"
        context['btn_href'] = reverse_lazy('ledger:accounts_book')
        context['btn_text'] = 'План счетов'
        context['menu_list'] = MENU
        return context

    def get_object(self):
        """ Переопределяем стандартное получение объекта для UpdateView по pk или slug на number

            Посмотрел здесь:
            https://stackru.com/questions/54206946/django-detailview-putanitsa-v-funktsii-getobject
        """
        return get_object_or_404(LedgerAccount, number=self.kwargs.get('number'))


class AccountDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'account.delete_choice'
    model = LedgerAccount
    template_name = 'ledger/account_delete.html'
    # TODO: разобраться почему не работает reverse('ledger:accounts_book')
    success_url = reverse_lazy('ledger:accounts_book')
    context_object_name = 'account'

    def get_context_data(self, **kwargs):
        """ Переменные шаблона

        title =     title сайта; заголовок navbar content
        btn_href =  ссылка для кнопки navbar content
        btn_text =  текст для кнопки navbar content
        cart_text = текст info-cart, вызываемой в случае отсутствия записей
        menu_list = список элементов dropdown меню: {item-group, item-text, item-url}
        """
        context = super().get_context_data(**kwargs)
        context['title'] = f"Удалить счет: {context['account'].number} {context['account'].name}"
        context['btn_href'] = reverse_lazy('ledger:accounts_book')
        context['btn_text'] = 'План счетов'

        # TODO: Добавить проверку, т.к. если проводка сохранена с пустыми счетами, выдает ошибку
        context['cart_text'] = f"Счет: {context['account'].number} {context['account'].name}, " \
                               f"до удаления связанных с ним {context['account'].get_refs()} движений " \
                               f"в журнале проводок, удалить нельзя!"
        context['menu_list'] = MENU
        return context

    def get_object(self):
        """ Переопределяем стандартное получение объекта для DetailView по pk или slug на number

            Посмотрел здесь:
            https://stackru.com/questions/54206946/django-detailview-putanitsa-v-funktsii-getobject
        """
        return get_object_or_404(LedgerAccount, number=self.kwargs.get('number'))


class EntriesJournalListView(LoginRequiredMixin, ListView):
    model = LedgerEntry
    template_name = 'ledger/entries_journal.html'
    context_object_name = 'entries'

    def get_context_data(self, **kwargs):
        """ Переменные шаблона

        title =     title сайта; заголовок navbar content
        btn_href =  ссылка для кнопки navbar content
        btn_text =  текст для кнопки navbar content
        cart_text = текст info-cart, вызываемой в случае отсутствия записей
        menu_list = список элементов dropdown меню: {item-group, item-text, item-url}
        """
        context = super().get_context_data(**kwargs)
        context['title'] = 'Журнал проводок'
        context['btn_href'] = reverse_lazy('ledger:entry_create')
        context['btn_text'] = 'Новая проводка'
        context['cart_text'] = 'В журнале проводок нет записей!'
        context['menu_list'] = MENU
        return context


class EntryView(LoginRequiredMixin, DetailView):
    permission_required = 'entry.view_choice'
    model = LedgerEntry
    template_name = 'ledger/entry.html'
    context_object_name = 'entry'

    def get_context_data(self, **kwargs):
        """ Переменные шаблона

        title =     title сайта; заголовок navbar content
        btn_href =  ссылка для кнопки navbar content
        btn_text =  текст для кнопки navbar content
        menu_list = список элементов dropdown меню: {item-group, item-text, item-url}
        """
        context = super().get_context_data(**kwargs)
        context['title'] = 'Проводка'
        context['btn_href'] = reverse_lazy('ledger:entries_journal')
        context['btn_text'] = 'Журнал проводок'
        context['menu_list'] = MENU
        return context


class EntryCreateView(PermissionRequiredMixin, CreateView):
    # TODO: сделать валидацию, в т.ч. проверку на ввод счета-1 и счета-2
    # TODO: изучить возможность добавить проверку корректности проводок (пример: +50 +60, а не +60 +50)
    permission_required = 'entry.add_choice'
    model = LedgerEntry
    template_name = 'ledger/entry_edit.html'  # entry_create.html
    context_object_name = 'entry'
    form_class = LedgerEntryForm

    def get_context_data(self, **kwargs):
        """ Переменные шаблона

        title =     title сайта; заголовок navbar content
        btn_href =  ссылка для кнопки navbar content
        btn_text =  текст для кнопки navbar content
        menu_list = список элементов dropdown меню: {item-group, item-text, item-url}
        """
        context = super().get_context_data(**kwargs)
        context['title'] = 'Создать проводку'
        context['btn_href'] = reverse_lazy('ledger:entries_journal')
        context['btn_text'] = 'Журнал проводок'
        context['menu_list'] = MENU
        return context


class EntryUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'entry.change_choice'
    model = LedgerEntry
    template_name = 'ledger/entry_edit.html'
    context_object_name = 'entry'
    form_class = LedgerEntryForm

    def get_context_data(self, **kwargs):
        """ Переменные шаблона

        title =     title сайта; заголовок navbar content
        btn_href =  ссылка для кнопки navbar content

balukaa/ledger/templates/ledger/account.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ title }}{{ block.super }}{% endblock %}
{% block content %}
    {# ------- ЛОКАЛЬНОЕ МЕНЮ ------- #}
    {% include 'ledger/includes/_nav_table.html' %}
    {# ------- ОТОБРАЖЕНИЕ ДЕТАЛЕЙ СЧЕТА ------- #}
    {# TODO: Переделать c table на div flex #}
    <div class="d-flex flex-row justify-content-center">
        <table class="table table-striped table-hover table-bordered table-sm ledger-table-account">
            <thead>
                <tr>
                    <th scope="col">Поле</th>
                    <th scope="col">Значение</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><code>id</code></td>
                    <td><code>{{ account.id }}</code></td>
                </tr>
                <tr>
                    <td>Номер</td>
                    <td>{{ account.number }}</td>
                </tr>
                <tr>
                    <td>Имя</td>
                    <td>{{ account.name }}</td>
                </tr>
                <tr>
                    <td>Полное имя</td>
                    <td>{{ account.full_name }}</td>
                </tr>
                <tr>
                    <td>Тип</td>
                    <td>{{ account.get_type_display }}</td>
                </tr>
                <tr>
                    <td><code>Ссылок</code></td>
                    <td><code>{{ account.get_refs }}</code></td>
                </tr>
            </tbody>
        </table>
    </div>
    {# ------- КНОПКИ УПРАВЛЕНИЯ ------- #}
    {# TODO: Перенести в локальное меню #}
    <div class="d-flex flex-row justify-content-center">
        {# ------- КНОПКА НАЗАД ------- #}
        {% if request.META.HTTP_REFERER %}
            {% include 'ledger/includes/_btn_back.html' %}
        {% endif %}
        {# ------- КНОПКА ИЗМЕНИТЬ ------- #}
        <a  class="btn btn-outline-primary mx-1"
            href="{% url 'ledger:account_update' account.number %}"
        >
            <img src="{% static 'balukaa/images/pencil-square.svg' %}">
            <span class="mx-1">Изменить</span>
        </a>
        {# ------- КНОПКА УДАЛИТЬ, ЕСЛИ НЕТ ПРОВОДОК ПО СЧЕТУ ------- #}
        {% if account.get_refs == 0 %}
        <a  class="btn btn-outline-primary mx-1"
            href="{% url 'ledger:account_delete' account.number %}"
        >
            <img src="{% static 'balukaa/images/x-square.svg' %}">
            <span class="mx-1">Удалить</span>
        </a>
        {% endif %}
        {# ------- КНОПКА КАРТОЧКА СЧЕТА ------- #}
        <a  class="btn btn-outline-primary mx-1"
            href="{% url 'ledger:account_card_report' account.number %}"
        >
            <img src="{% static 'balukaa/images/card-text.svg' %}">
            <span class="mx-1">Карточка счета</span>
        </a>
    </div>
{% endblock %}

balukaa/ledger/templates/ledger/account_edit.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ title }}{{ block.super }}{% endblock %}
{% block content %}
    {# ------- ЛОКАЛЬНОЕ МЕНЮ ------- #}
    {% include 'ledger/includes/_nav_table.html' %}
    {# ------- ФОРМА ------- #}
    {# TODO: верификация #}
    <div class="d-flex justify-content-center">
        <div class="card bg-light mb-3 ledger-cart">
            <div class="card-body">
                <form method="post">{% csrf_token %}
                    {{ form.as_table }}
                    {% include 'ledger/includes/_btn_save_cancel.html' %}
                </form>
            </div>
        </div>
    </div>
{% endblock %}

balukaa/ledger/templates/ledger/accounts_book.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ title }}{{ block.super }}{% endblock %}
{% block content %}
    {# ------- ЛОКАЛЬНОЕ МЕНЮ ------- #}
    {% include 'ledger/includes/_nav_table.html' %}
    {# ------- ОТОБРАЖЕНИЕ СПРАВОЧНИКА ------- #}
    {# TODO: Переделать c table на div flex #}
    <div class="d-flex justify-content-center">
        {% if accounts %}
        <table class="table table-striped table-hover table-bordered table-sm">
            <thead class="ledger-table-th table-success">
                <tr>
                    <th scope="col"><code>id</code></th>
                    <th scope="col">Номер</th>
                    <th scope="col">Имя</th>
                    <th scope="col">Полное имя</th>
                    <th scope="col" title="Число проводок со счетом"><code>Движений</code></th>
                    <th scope="col" colspan="2"><code>Действие</code></th>
                </tr>
            </thead>
            <tbody>
                {% for account in accounts %}
                <tr>
                    <td class="ledger-table-number"><code>{{ account.id }}</code></td>
                    <td class="ledger-table-number">
                        {{ account.number }}
                        {% include 'ledger/includes/_account_type_sign_tooltip.html' %}
                    </td>
                    <td class="ledger-table-text">
                        {{ account.name }}
                        {% include 'ledger/includes/_account_type_sign_tooltip.html' %}
                    </td>
                    <td class="ledger-table-text">
                        {{ account.full_name }}
                        {% include 'ledger/includes/_account_type_sign_tooltip.html' %}
                    </td>
                    <td class="ledger-table-number">
                        {% if account.get_refs != 0 %}
                        <span class="badge bg-primary">
                            {{ account.get_refs }}
                        </span>
                        {% else %}
                        <span class="badge text-primary bg-light">
                            -
                        </span>
                        {% endif%}
                    </td>
                    <td>
                        {# КНОПКА ПРОСМОТРА ТЕКУЩЕГО СЧЕТА #}
                        <a  href="{% url 'ledger:account_view' account.number %}"
                            title = "Посмотреть счет {{ account.number }}"
                            role="button"
                        ><img src="{% static 'balukaa/images/eye.svg' %}"></a>
                        {# КНОПКА РЕДАКТИРОВАНИЯ ТЕКУЩЕГО СЧЕТА #}
                        <a  href="{% url 'ledger:account_update' account.number %}"
                            title = "Редактировать счет {{ account.number }}"
                            role="button"
                        ><img src="{% static 'balukaa/images/pencil-square.svg' %}"></a>
                        {# КНОПКА УДАЛЕНИЯ ТЕКУЩЕГО СЧЕТА, ЕСЛИ ПО НЕМУ НЕТ ПРОВОДОК #}
                        {% if account.get_refs == 0 %}
                        <a  href="{% url 'ledger:account_delete' account.number %}"
                            title = "Удалить счет {{ account.number }}"
                        ><img src="{% static 'balukaa/images/x-square.svg' %}"></a>
                        {% endif %}
                    </td>
                    <td>
                        {# КНОПКА ОТКРЫТИЯ КАРТОЧКИ ТЕКУЩЕГО СЧЕТА #}
                        <a  href="{% url 'ledger:account_card_report' account.number %}"
                            title = "Открыть карточку счета {{ account.number }}"
                            role="button"
                        ><img src="{% static 'balukaa/images/card-text.svg' %}"></a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
            {# ------- СООБЩЕНИЕ, ЕСЛИ НЕТ ЗАПИСЕЙ ------- #}
            {% include 'includes/_cart_info.html' %}
        {% endif %}
    </div>
{% endblock %}

balukaa/ledger/templates/ledger/entries_journal.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ title }}{{ block.super }}{% endblock %}
{% block content %}
    {# ------- ЛОКАЛЬНОЕ МЕНЮ ------- #}
    {% include 'ledger/includes/_nav_table.html' %}
    {# ------- ОТОБРАЖЕНИЕ ЖУРНАЛА ------- #}
    {# TODO: Переделать c table на div flex #}
    <div class="d-flex justify-content-center">
        {% if entries %}
        <table class="table table-striped table-hover table-bordered table-sm">
            <thead class="ledger-table-th table-success">
                <tr>
                    <th scope="col"><code title="Состояние проводки: Включена или Выключена">?</code></th>
                    <th scope="col"><code>id</code></th>
                    <th scope="col">Дата</th>
                    <th scope="col" colspan="2">Счет 1&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;&nbsp;&nbsp;&nbsp;Счет 2</th>
                    <th scope="col">Сумма</th>
                    <th scope="col">Комментарий</th>
                    <th scope="col"><code>Действие</code></th>
                </tr>
            </thead>
            <tbody>
                {% for entry in entries %}
                <tr>
                    <td class="ledger-table-type">
                        <code data-toggle="tooltip"
                              data-placement="right"
                              title="Проводка: {{ entry.get_status_display }}"
                        >
                            {% if entry.status %}
                                <img src="{% static 'balukaa/images/toggle-on.svg' %}">
                            {% else %}
                                <img src="{% static 'balukaa/images/toggle-off.svg' %}">
                            {% endif %}
                        </code>
                    </td>
                    <td class="ledger-table-number"><code>{{ entry.id }}</code></td>
                    <td class="ledger-table-date">{{ entry.date|date:'d.m.Y' }}</td>
                    <td class="ledger-table-number">
                        <code>{{ entry.get_account_one_type_symbol }}</code>{{ entry.account_one.number }}
                        <code>{{ entry.get_account_two_type_symbol }}</code>{{ entry.account_two.number }}
                    </td>
                    <td class="ledger-table-text">
                        <code>{{ entry.get_account_one_type_symbol }}</code>{{ entry.account_one.name }}
                        <code>{{ entry.get_account_two_type_symbol }}</code>{{ entry.account_two.name }}
                    </td>
                    <td class="ledger-table-amount">{{ entry.amount }}</td>
                    <td class="ledger-table-text">{{ entry.comment }}</td>
                    <td>
                        {# КНОПКА ПРОСМОТРА ТЕКУЩЕЙ ПРОВОДКИ #}
                        <a href="{% url 'ledger:entry_view' entry.id %}"
                           title = "Посмотреть проводку c id={{ entry.id }}"
                        ><img src="{% static 'balukaa/images/eye.svg' %}"></a>
                        {# КНОПКА РЕДАКТИРОВАНИЯ ТЕКУЩЕЙ ПРОВОДКИ #}
                        <a href="{% url 'ledger:entry_update' entry.id %}"
                           title = "Редактировать проводку c id={{ entry.id }}"
                        ><img src="{% static 'balukaa/images/pencil-square.svg' %}"></a>
                        {# КНОПКА УДАЛЕНИЯ ТЕКУЩЕЙ ПРОВОДКИ #}
                        <a href="{% url 'ledger:entry_delete' entry.id %}"
                           title = "Удалить проводку c id={{ entry.id }}"
                        ><img src="{% static 'balukaa/images/x-square.svg' %}"></a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
            {# ------- СООБЩЕНИЕ, ЕСЛИ НЕТ ЗАПИСЕЙ ------- #}
            {% include 'includes/_cart_info.html' %}
        {% endif %}
    </div>
{% endblock %}